development:
  sessions:
    default:
      database: collaboration_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: collaboration_test
      hosts:
        - localhost:27017